FROM osixia/phpldapadmin:0.7.2

LABEL maintainer="sumit_ramteke@persistent.com"

EXPOSE 443
EXPOSE 80

ENV LDAP_ORGANISATION="Persistent Ltd"

# COPY bootstrap.ldif /container/service/slapd/assets/config/bootstrap/ldif/50-bootstrap.ldif
